# 注册中心
eureka:
  #  server:
  #    enable-self-preservation: false  #自我保护机制 (不推荐关闭)
  client:
    service-url:
      defaultZone: http://localhost:12001/eureka/
  #      defaultZone: http://eureka1.com:12001/eureka/,http://eureka2.com:12002/eureka/,http://eureka3.com:12003/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port} #更改主机显示名称
    prefer-ip-address: true #显示IP

server:
  name:
    base: base-service
    eureka: eureka-server
  port:
    base: 16001
    eureka1: 12001
    eureka2: 12002
    eureka3: 12003
